In [3]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.datasets import load_boston

dt= load_boston()
X=dt.data
Y=dt.target

In [5]:
df_x=pd.DataFrame(X,columns=dt.feature_names)
df_x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48
505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88

In [6]:
df_y=pd.DataFrame(Y,columns=["target"])
df_y

     target
0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
..      ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9

[506 rows x 1 columns]

In [7]:
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(df_x,df_y, test_size=0.2) #

# Model train and test

In [8]:
#Import knearest neighbors Classifier model

from sklearn.neighbors import KNeighborsRegressor

#Create KNN Classifier
knn = KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=7, p=2,
                    weights='uniform')

#Train the model using the training sets
knn.fit(X_train, y_train)


#Predict the response for test dataset

knn

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=7, p=2,
                    weights='uniform')

In [16]:
#Import knearest neighbors Classifier model

from sklearn.neighbors import KNeighborsRegressor

#Create KNN Classifier
knn2 = KNeighborsRegressor(n_neighbors=7,weights='distance')



#Train the model using the training sets
knn2.fit(X_train, y_train)


#Predict the response for test dataset
knn2
#improve performance---

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                    weights='distance')

In [10]:
y_pred1 = knn.predict(X_test)
y_pred1


y_pred2 = knn2.predict(X_test)
y_pred2

# ---   y_pred1-y_test==error

array([[20.11174661],
       [21.66953752],
       [20.82142191],
       [22.71424397],
       [16.26689745],
       [29.2492722 ],
       [26.75097017],
       [23.55060966],
       [25.36439185],
       [14.20497356],
       [25.26014954],
       [22.0029675 ],
       [35.95404456],
       [18.39818765],
       [14.65137011],
       [18.6186199 ],
       [20.95657896],
       [42.725953  ],
       [21.54461475],
       [20.24398138],
       [ 8.53761304],
       [20.24009817],
       [37.59527312],
       [22.4615429 ],
       [30.25383799],
       [11.26226665],
       [15.08925753],
       [17.5673352 ],
       [24.48799515],
       [25.03070364],
       [12.43330699],
       [24.18745339],
       [20.30547327],
       [29.28111813],
       [20.68366968],
       [24.86733211],
       [16.72564341],
       [22.80176132],
       [18.95303637],
       [22.81627628],
       [35.78862269],
       [22.31863983],
       [24.17649825],
       [11.87012645],
       [22.95071104],
       [26.37100273],
       [23.2379597 ],
       [21.49351292],
       [27.9019369 ],
       [25.95759159],
       [38.31714893],
       [12.54847096],
       [23.33645506],
       [22.23032826],
       [23.90617842],
       [ 9.44064813],
       [31.09295354],
       [22.23491912],
       [20.20685958],
       [18.23710244],
       [27.7848209 ],
       [13.75909679],
       [15.47670996],
       [16.42829248],
       [18.53248945],
       [21.30884834],
       [23.07294196],
       [19.55950084],
       [19.89222775],
       [20.5453742 ],
       [27.13367841],
       [11.54672158],
       [27.7393124 ],
       [30.46295726],
       [36.06877782],
       [23.9243762 ],
       [27.29530991],
       [29.18188596],
       [28.56701414],
       [15.2879114 ],
       [27.00713035],
       [13.073691  ],
       [39.13352792],
       [22.76892483],
       [21.92735293],
       [20.2995563 ],
       [28.29013544],
       [22.00847557],
       [13.88896839],
       [17.48847301],
       [17.63908522],
       [23.16642254],
       [ 9.73990914],
       [33.09710291],
       [24.83189184],
       [28.56316643],
       [17.9658445 ],
       [28.16876226],
       [29.97442766],
       [25.58314369],
       [16.3574727 ],
       [20.19072987]])

In [11]:
from sklearn.metrics import mean_squared_error 
from math import sqrt
#RMSE=sqrt(MSE)

import matplotlib.pyplot as plt
%matplotlib inline
actual=y_test

In [12]:
error1 = sqrt(mean_squared_error(actual,y_pred1)) #calculate rmse
error1

6.608286750854006

In [13]:
error2 = sqrt(mean_squared_error(y_test,y_pred2)) #calculate rmse
error2

6.095014977579151

In [14]:
from sklearn import metrics
print("Accuracy:",metrics.r2_score(y_test, y_pred))

NameError: name 'y_pred' is not defined

In [ ]:
#GridSearch CV

from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':[1,3,5,7,9,11,21]}

knn1 = KNeighborsRegressor(n_neighbors=1)
knn2 = KNeighborsRegressor(n_neighbors=3)
knn3 = KNeighborsRegressor(n_neighbors=5)
knn4 = KNeighborsRegressor(n_neighbors=7)
knn5 = KNeighborsRegressor(n_neighbors=9)
knn6 = KNeighborsRegressor(n_neighbors=11)
knn7 = KNeighborsRegressor(n_neighbors=21)


model = GridSearchCV(knn, params, cv=5)
model.fit(X_train,y_train)

model

In [ ]:
knn = KNeighborsRegressor(n_neighbours=3)

KFold(knn, cv=5)

In [ ]:
model.cv_results_

In [ ]:

print(model.best_params_,model.best_score_,model.best_estimator_)

In [ ]:
#GridSearch CV

from sklearn.model_selection import GridSearchCV
params = {'weights':['uniform','distance'],
         'n_neighbors':[1,3,5,7,9]}

knn = KNeighborsRegressor()



model = GridSearchCV(knn, params, cv=5)
model.fit(X_train,y_train)

model.cv_results_

In [ ]:

#pd.concat([df_y_pred,df_y_test],axis=1,sort=True)#,ignore_index=True, sort=False)

# evaluation

In [ ]:
error_rate = []
# Will take some time
for i in range(1,40):
 
    knn = KNeighborsRegressor(n_neighbors=i)
    knn.fit(X_train,y_train)
    pred_i = knn.predict(X_test)
    
    error_rate.append(sqrt(mean_squared_error(y_test,y_pred2)))
     
#     np.mean(pred_i != y_test))

In [ ]:
plt.figure(figsize=(10,6))
plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',
 markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('Error Rate')