In [42]:
#import statsmodels
import statsmodels.api as sm

import numpy as np

import pandas as pd

import statsmodels.api as sm

In [43]:

dt1=sm.datasets.cancer.load_pandas().data
type(dt1)
dt1.describe()

           cancer    population
count  301.000000    301.000000
mean    39.857143  11288.056478
std     50.977801  13780.010088
min      0.000000    445.000000
25%     11.000000   2935.000000
50%     22.000000   6445.000000
75%     48.000000  13989.000000
max    360.000000  88456.000000

In [44]:
ll=sm.datasets.longley.load_pandas()
dt=sm.datasets.longley.load_pandas().data

In [45]:
%matplotlib inline
import matplotlib.pyplot as plt
x=ll.POP
y=ll.TOTEMP
plt.plot(x,y)


#plt.show()

AttributeError: 'Dataset' object has no attribute 'POP'

In [ ]:
sm.datasets.longley.DESCRLONG

In [60]:

#dt=sm.datasets.longley.load_pandas().data

df = sm.datasets.get_rdataset("Arthritis", "vcd").data
#https://github.com/vincentarelbundock/Rdatasets/tree/master/csv/vcd
df.head()

   ID Treatment   Sex  Age Improved
0  57   Treated  Male   27     Some
1  46   Treated  Male   29     None
2  77   Treated  Male   30     None
3  17   Treated  Male   32   Marked
4  36   Treated  Male   46   Marked

In [ ]:
import pandas as pd
#https://github.com/vincentarelbundock/Rdatasets/tree/master/csv/vcd/Arthritis.csv
pd.read_csv('https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/vcd/Arthritis.csv')

In [ ]:
??sm.datasets.get_rdataset

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 10000)

In [ ]:
#??sm.datasets.get_rdataset
df

In [47]:

#dt=sm.datasets.longley.load_pandas().data

df = sm.datasets.get_rdataset("Arthritis", "vcd").data
#https://github.com/vincentarelbundock/Rdatasets/tree/master/csv/vcd
df.head()

data = df[["Treatment", "Improved"]]

data

   Treatment Improved
0    Treated     Some
1    Treated     None
2    Treated     None
3    Treated   Marked
4    Treated   Marked
5    Treated   Marked
6    Treated     None
7    Treated   Marked
8    Treated     None
9    Treated     None
10   Treated     None
11   Treated     Some
12   Treated     None
13   Treated   Marked
14   Treated     None
15   Treated     None
16   Treated     Some
17   Treated     None
18   Treated   Marked
19   Treated     None
20   Treated   Marked
21   Treated   Marked
22   Treated   Marked
23   Treated   Marked
24   Treated   Marked
25   Treated   Marked
26   Treated   Marked
27   Treated     None
28   Treated   Marked
29   Treated   Marked
30   Treated   Marked
31   Treated   Marked
32   Treated     Some
33   Treated   Marked
34   Treated   Marked
35   Treated   Marked
36   Treated     Some
37   Treated   Marked
38   Treated     None
39   Treated     Some
40   Treated     Some
41   Placebo     None
42   Placebo     None
43   Placebo     None
44   Placebo     None
45   Placebo     None
46   Placebo     None
47   Placebo     None
48   Placebo     None
49   Placebo     None
50   Placebo     None
51   Placebo   Marked
52   Placebo     None
53   Placebo     None
54   Placebo     None
55   Placebo     Some
56   Placebo     None
57   Placebo   Marked
58   Placebo     None
59   Placebo     None
60   Placebo     None
61   Placebo     None
62   Placebo     None
63   Placebo     None
64   Placebo     None
65   Placebo     None
66   Placebo     None
67   Placebo     None
68   Placebo   Marked
69   Placebo   Marked
70   Placebo     None
71   Placebo     Some
72   Placebo     Some
73   Placebo     Some
74   Placebo   Marked
75   Placebo     None
76   Placebo     Some
77   Placebo     None
78   Placebo   Marked
79   Placebo     None
80   Placebo     None
81   Placebo     Some
82   Placebo     Some
83   Placebo   Marked

In [48]:
table = sm.stats.Table.from_data(data)
print(table)

A 2x3 contingency table with counts:
[[ 7. 29.  7.]
 [21. 13.  7.]]

In [49]:

newdata=ll
newdata

# Machine Learning starts here

In [50]:
#MODELs

#features
X=newdata.exog
X=X.drop(['POP'],axis=1)

In [51]:

#target
y=newdata.endog

#actual model building
model = sm.OLS(y, X)
#sklearn
results = model.fit()

results.summary2()

C:\Users\Deepak\anaconda33\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary2.Summary'>
"""
                        Results: Ordinary least squares
================================================================================
Model:                  OLS              Adj. R-squared (uncentered): 1.000
Dependent Variable:     TOTEMP           AIC:                         247.5833
Date:                   2020-06-07 16:50 BIC:                         251.4462
No. Observations:       16               Log-Likelihood:              -118.79
Df Model:               5                F-statistic:                 5.719e+04
Df Residuals:           11               Prob (F-statistic):          6.88e-24
R-squared (uncentered): 1.000            Scale:                       2.3937e+05
------------------------------------------------------------------------------------
               Coef.      Std.Err.        t        P>|t|        [0.025       0.975]
------------------------------------------------------------------------------------
GNPDEFL       54.6161     102.0071      0.5354     0.6030     -169.9000     279.1321
GNP            0.0343       0.0101      3.3840     0.0061        0.0120       0.0566
UNEMP         -0.8701       0.2404     -3.6200     0.0040       -1.3991      -0.3411
ARMED         -0.5552       0.2869     -1.9349     0.0791       -1.1867       0.0764
YEAR          25.9330       3.0434      8.5210     0.0000       19.2345      32.6316
--------------------------------------------------------------------------------
Omnibus:                    4.743            Durbin-Watson:               0.971
Prob(Omnibus):              0.093            Jarque-Bera (JB):            2.166
Skew:                       0.720            Prob(JB):                    0.338
Kurtosis:                   4.085            Condition No.:               333312
================================================================================
* The condition number is large (3e+05). This might indicate             strong
multicollinearity or other numerical problems.
"""

In [53]:
print('Parameters: ', results.params)
#\n
print('R2: ', results.rsquared)

Parameters:  GNPDEFL    54.616059
GNP         0.034313
UNEMP      -0.870083
ARMED      -0.555167
YEAR       25.933029
dtype: float64
R2:  0.999961530442224

In [72]:
#errors

predicted=results.predict()
error=y-predicted
RMSE
MSE
MASE
#print(y)
#newdata.data

0      191.735514
1     -299.476437
2       56.582649
3     -204.311441
4     -369.752181
5     -570.409133
6       -6.413256
7      139.765485
8      373.305129
9     1077.324413
10     412.875902
11     -32.196336
12    -126.174862
13      68.354357
14     -13.301982
15    -698.410474
Name: TOTEMP, dtype: float64

In [54]:
results.save('model.pkl')

#PMML and PFA
#results2=sm.load('model.pkl')
#pickel files in python

TRAIN
110 iterations----number of records 100
100th -- Coeficients final
B0
B1
B2
100 records

200 itertaions=2 epochs

#2 EPOCH ==100 records

In [55]:
import os
os.getcwd()

#REINFORCEMENT LEARNING

'C:\\Users\\Deepak'